version: "3.5"

services:
  php_fpm:
      build: .
      container_name: blog_php_fpm
      working_dir: /usr/share/nginx/blog
      volumes:
          - ./application:/usr/share/nginx/blog

  nginx:
      image: nginx:1.15
      container_name: blog_nginx
      working_dir: /usr/share/nginx/blog
      ports:
          - "8080:80"
      volumes:
          - ./application:/usr/share/nginx/blog
          - ./config/nginx/:/etc/nginx/conf.d/

  mysql:
      image: mysql:5.7
      container_name: blog_mysql
      environment:
        - MYSQL_DATABASE=blog
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_USER=blog
        - MYSQL_PASSWORD=password